config:
  azure-native:location: centralindia
  scribbl:enableCustomDomain: "false"
  scribbl:secretKeyBase:
    secure: AAABAHDbr/6AHxfuBMcz3uHuRLf65b01d4GXdg5qgZHXGLZet2KXgP1t7fWy7eN2ZeV3hVW7vBxCmiqdqTvpwOSCBgoBi9byuRkaBLnF0D6qJdW2vSrZIcY/Qucj9b+FSB5YGbLR8ymlxfDJGOmApGkgsojdePyA
