config:
  scribbl:secretKeyBase:
    secure: AAABACcb7jj5QNrejlO+JI7CiofxUwsKzgT5JdKLRMBufxqIMon9YQKkGAAG8qF/6S2G0YYLjtsA1/PoG7IPw3lemwemCADdm6j1Ib3IoxfYNfBdW5zcS/NGPz1SD9gANulTQhI7BwkV7MkaUiniN1iFXaYjY2Id
  azure-native:location: centralindia
  scribbl:enableCustomDomain: "true"
