name: Build and Push Auth

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'auth/**'
      - '.github/workflows/build-auth.yaml'
  release:
    types: [published]

env:
  REGISTRY: ghcr.io

jobs:
  build-auth:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-auth
          tags: |
            type=pep440,pattern={{version}},value=${{ github.ref_name }},enable=${{ github.event_name == 'release' }}
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.event_name == 'release' }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./auth
          dockerfile: Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} 